### ISSUE TITLE
Keeping previous shares intact

### ISSUE THREAD

**Issue by HP41** [bertvv/ansible-role-samba#10]
As far as I can see in this role it doesn't keep previous shares intact.
For eg, if the role is called as a dependency to another, it'll wipe out any other shares previously defined. 

It can be hard to find out if samba has been configured or shares defined therefore to keep things clean maybe the onus should be on the user to define if it should do a `config reset` or `just add share info`. A flag perhaps?

**Comment by bertvv** [comment]
This behaviour is intentional. This role has the responsibility to take complete control over the Samba configuration and should be the *single source of truth* about the intended state of the Samba file server. This role should not be applied to a machine that already has some Samba configuration, either by another role, or -worse- edited manually.

If you can show a specific and valid case where this role interferes with another role, I'll try to fix that. 

Also, if this role is depended upon by another one, I would love to hear about that...
