### ISSUE TITLE
adding users fails

### ISSUE THREAD

**Issue by stefangweichinger** [bertvv/ansible-role-samba#38]
Found your role when searching for a way to create samba users ... unfortunately it fails.
Do you assume that the underlying shell/system account already exists? Otherwise I'd have to add a task doing "useradd" before ...

**Comment by bertvv** [comment]
Indeed, the system account should already exist. This is intentional. Creating a system user involves stuff that is not a concern of this role, e.g. setting the shell, group membership, etc. For my own servers, I use another role for this: [bertvv.rh-base](https://galaxy.ansible.com/bertvv/rh-base).
